### ISSUE TITLE
App Analysis Exception

### ISSUE THREAD

**Issue by zikcheng** [miwong/IntelliDroid#1]
Hi,
Every time I run the command `./IntelliDroidAppAnalysis -o <output directory> <preprocessed app directory>
`,exception `java.lang.IllegalArgumentException`occurs.For example,after preprocessing the apk file com.github.wakhub.tinyclock_5.apk which is from f-droid.org,I run the command `./IntelliDroidAppAnalysis -o output/ ~/com.github.wakhub.tinyclock_5/`,the exception information shows as below:

```
Exception in thread "main" java.lang.IllegalArgumentException: class <Extension,Ljava/lang/Object> is invalid, unexpected classloader
    at com.ibm.wala.ipa.cha.ClassHierarchy.addClass(ClassHierarchy.java:300)
    at com.ibm.wala.ipa.cha.ClassHierarchy.addAllClasses(ClassHierarchy.java:280)
    at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:241)
    at com.ibm.wala.ipa.cha.ClassHierarchy.<init>(ClassHierarchy.java:177)
    at com.ibm.wala.ipa.cha.ClassHierarchy.make(ClassHierarchy.java:1217)
    at com.ibm.wala.ipa.cha.ClassHierarchy.make(ClassHierarchy.java:1197)
    at intellidroid.appanalysis.IntelliDroidAppAnalysis.analyze(IntelliDroidAppAnalysis.java:230)
    at intellidroid.appanalysis.IntelliDroidAppAnalysis.main(IntelliDroidAppAnalysis.java:190)
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/java/jdk1.8.0_91/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

Looking forward to your reply.Thank you very much.

**Comment by hao-fu** [comment]
I do not think this issue is related to [https://github.com/miwong/IntelliDroid/issues/4](url).
The problem is resolved by changing my jdk from 8 to 7.
